version: '4.0'
services:
    web:
        platform: linux/amd64 # Explicitly set for TDX
        image: mattdlockyer/based-agent-test:latest@sha256:055c88f43b2c3ca73044dcbf956e08c17e79c323690be634ecaf45bf9c64b066
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
